name: Build repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (debug)
      run: cargo build --verbose
    - name: Run tests (debug)
      run: cargo test --verbose
    - name: Build (release)
      run: cargo build --release --verbose
    - name: Run tests (release)
      run: cargo test --release --verbose
